# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  release:
    types:
      - published  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Set .env values
      run: |
        sed -i -e 's/APP_ENV=local/APP_ENV=prod/g' .env
        sed -i -e 's/APP_DEBUG=true/APP_ENV=false/g' .env
        sed -i -e 's/APP_URL=http:\/\/localhost/APP_ENV=https:\/\/grap-sim.com/g' .env
        sed -i -e 's/DB_CONNECTION=mysql/DB_CONNECTION=${{ secrets.DB_CONNECTION }}/g' .env
        sed -i -e 's/DB_HOST=127.0.0.1/DB_HOST=${{ secrets.DB_HOST }}/g' .env
        sed -i -e 's/DB_PORT=3306/DB_PORT=${{ secrets.DB_PORT }}/g' .env
        sed -i -e 's/DB_DATABASE=homestead/DB_DATABASE=${{ secrets.DB_DATABASE }}/g' .env
        sed -i -e 's/DB_USERNAME=homestead/DB_USERNAME=${{ secrets.DB_USERNAME }}/g' .env
        sed -i -e 's/DB_PASSWORD=secret/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/g' .env

    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader --no-dev

    - name: Install NPM Dependencies
      run: npm install

    - name: Compile NPM Dependencies
      run: npm run prod

    - name: Copy file via scp to PROD host
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "."
        target: ${{ secrets.DEPLOY_FOLDER }}

    - name: Running post-copy commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
        script: |
          php ${{ secrets.DEPLOY_FOLDER }}/artisan key:generate
          chmod -R 777 storage bootstrap/cache
          php ${{ secrets.DEPLOY_FOLDER }}/artisan config:cache
          php ${{ secrets.DEPLOY_FOLDER }}/artisan route:cache
          php ${{ secrets.DEPLOY_FOLDER }}/artisan view:cache
